language: node_js
node_js: 
  - "stable"

script:
  - npm run build
 
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
  branch: master
