language: node_js
node_js: 
  - lts/*

script:
  - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
  - unzip butler.zip
  - chmod +x butler
  - ./butler -V
  - rm butler.zip
  - npm install
  - npm run build
  - ./butler push public baj/txtdit:html5
 
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
  branch: master
